language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
script:
  - CI=false npm run build
  - npm test
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: esman
  run:
    - "heroku ps:scale web=1"