version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
      - run: npm run build
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
      - run: npm run test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
          requires
            - build #wait for build to complete successfully before running